import { getSession, isAdmin, sessionStation } from "../auth.js";
import { hierarchy, dailyTrend } from "../data/reportData.js";
import { getSubmissions, submissionsFor } from "../data/store.js";
import { dashboardData } from "./dashboard.js";
import { ASSISTANT_WORKER_URL } from "../config.js";

const history = [];
const esc = value => String(value).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");

const workerUrl = () => ASSISTANT_WORKER_URL.trim().replace(/\/+$/, "");

const SUGGESTIONS = [
  "Which station filed the most FIRs?",
  "Summarise today's body vs other offences.",
  "Which stations have not submitted today's DCR?",
  "Where is chargesheet pendency the highest?"
];

function contextData() {
  const admin = isAdmin();
  const station = sessionStation();
  // dashboardData() is the exact function that renders the dashboards, so the
  // assistant answers from the same role-scoped rows and totals the user sees.
  const daily = dashboardData("daily");
  const monthly = dashboardData("monthly");
  return JSON.stringify({
    today: new Date().toISOString().slice(0, 10),
    viewer: admin ? { role: "HQ administrator", scope: "all police stations" } : { role: "station officer", station: station?.name },
    hierarchy,
    dailyDashboard: {
      scope: daily.scopeLabel,
      totals: { totalFir: daily.totals.total, bodyOffences: daily.totals.body, otherOffences: daily.totals.other },
      stations: daily.rows.map(({ name, zone, division, total, body, other, submitted, period }) => ({ station: name, zone, division, totalFir: total, bodyOffences: body, otherOffences: other, dcrSubmitted: Boolean(submitted), reportDate: submitted ? period : undefined }))
    },
    monthlyDashboard: {
      scope: monthly.scopeLabel,
      totals: { totalFir: monthly.totals.total, chargesheetsThisMonth: monthly.totals.currentCs, chargesheetsAgainstLastMonth: monthly.totals.lastCs, pendingThisMonth: monthly.totals.currentPending, pendingLastMonth: monthly.totals.lastPending },
      stations: monthly.rows.map(({ name, total, currentCs, lastCs, currentPending, lastPending, submitted, period }) => ({ station: name, totalFir: total, chargesheetsThisMonth: currentCs, chargesheetsAgainstLastMonth: lastCs, pendingThisMonth: currentPending, pendingLastMonth: lastPending, mcrSubmitted: Boolean(submitted), reportMonth: submitted ? period : undefined }))
    },
    cityWideDailyTrend: dailyTrend,
    filedReports: (admin ? getSubmissions() : submissionsFor(station?.name)).slice(0, 50)
  });
}

export function assistantView() {
  const session = getSession();
  const configured = Boolean(workerUrl());
  return `<main id="app-content" class="page-content page-width assistant-view">
    <div class="title-block"><h1>Reporting Assistant</h1><p>Ask questions about ${session?.role === "admin" ? "city-wide" : `${session?.station}'s`} DCR/MCR figures — answered by AI from portal data</p><i></i></div>
    ${configured ? "" : `<section class="form-panel setup-panel">
      <div class="panel-heading"><h2>Assistant temporarily unavailable</h2><span>Service provisioning</span></div>
      <p>The assistant service is being provisioned. Please check back shortly.</p>
    </section>`}
    <section class="form-panel chat-panel ${configured ? "" : "disabled"}">
      <div class="chat-log" data-chat-log aria-live="polite">
        ${history.length ? history.map(m => chatBubble(m.role, m.text)).join("") : `<div class="chat-empty">No questions yet. Try one of the suggestions below.</div>`}
      </div>
      <div class="chat-suggestions">${SUGGESTIONS.map(q => `<button type="button" class="chip" data-suggestion>${q}</button>`).join("")}</div>
      <form class="chat-form" data-chat-form>
        <input name="question" type="text" placeholder="Ask about FIRs, chargesheets, pendency…" autocomplete="off" ${configured ? "" : "disabled"} required>
        <button class="primary-button" type="submit" ${configured ? "" : "disabled"}>Ask</button>
      </form>
      <p class="data-note">Answers are generated by an AI model from the portal's demonstration dataset and may be imperfect. Verify against the dashboards.</p>
    </section>
  </main>`;
}

function chatBubble(role, text) {
  return `<div class="chat-msg ${role}"><span class="chat-who">${role === "user" ? "You" : "Assistant"}</span><div class="chat-text">${esc(text)}</div></div>`;
}

export function bindAssistant() {
  const form = document.querySelector("[data-chat-form]");
  if (!form) return;

  const log = document.querySelector("[data-chat-log]");
  const input = form.querySelector("input[name=question]");
  document.querySelectorAll("[data-suggestion]").forEach(chip => chip.addEventListener("click", () => {
    if (input.disabled) return;
    input.value = chip.textContent;
    form.requestSubmit();
  }));

  form.addEventListener("submit", async event => {
    event.preventDefault();
    const question = input.value.trim();
    if (!question) return;
    input.value = "";
    if (!history.length) log.innerHTML = "";
    history.push({ role: "user", text: question });
    log.insertAdjacentHTML("beforeend", chatBubble("user", question));
    log.insertAdjacentHTML("beforeend", `<div class="chat-msg assistant pending"><span class="chat-who">Assistant</span><div class="chat-text">Thinking…</div></div>`);
    log.scrollTop = log.scrollHeight;
    form.querySelector("button").disabled = true;
    let answer;
    try {
      const response = await fetch(workerUrl(), {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ question, history: history.slice(0, -1).slice(-10), context: contextData() })
      });
      const data = await response.json();
      answer = data.answer || data.error || "The assistant returned an empty response.";
    } catch {
      answer = "Could not reach the assistant service. Check the Worker URL and your connection.";
    }
    history.push({ role: "assistant", text: answer });
    log.querySelector(".pending").remove();
    log.insertAdjacentHTML("beforeend", chatBubble("assistant", answer));
    log.scrollTop = log.scrollHeight;
    form.querySelector("button").disabled = false;
    input.focus();
  });
}
